/**
 * 图标映射表
 * 用于 IconPicker 展示所有可选图标
 * 统一管理 lucide-vue-next 图标
 */

import * as LucideIcons from 'lucide-vue-next'
import { hasIcon, ICON_POOL } from './icon.pool'

// 图标分类定义 (基于 Lucide 官方分类)
export const iconCategories = {
  all: '全部',
  accessibility: '无障碍',
  account: '账户',
  animals: '动物',
  arrows: '箭头',
  brands: '品牌',
  buildings: '建筑',
  charts: '图表',
  communication: '通讯',
  connectivity: '连接',
  cursors: '光标',
  design: '设计',
  development: '开发',
  devices: '设备',
  emoji: '表情',
  files: '文件',
  food: '食物',
  gaming: '游戏',
  home: '家居',
  layout: '布局',
  mail: '邮件',
  maps: '地图',
  math: '数学',
  medical: '医疗',
  money: '金钱',
  music: '音乐',
  nature: '自然',
  navigation: '导航',
  notifications: '通知',
  people: '人物',
  photography: '摄影',
  science: '科学',
  security: '安全',
  shapes: '形状',
  shopping: '购物',
  social: '社交',
  sports: '运动',
  sustainability: '可持续',
  text: '文本',
  time: '时间',
  tools: '工具',
  transportation: '交通',
  travel: '旅行',
  weather: '天气',
} as const

export type IconCategory = keyof typeof iconCategories

// 图标中文名称映射(用于搜索)
export const iconChineseNames: Record<string, string[]> = {
  // 基础/常用
  Home: ['家', '首页', '主页', '房子'],
  User: ['用户', '人', '个人', '账户'],
  Users: ['用户组', '人群', '团队', '多人'],
  Settings: ['设置', '配置', '选项', '齿轮'],
  Search: ['搜索', '查找', '查询', '放大镜'],
  Menu: ['菜单', '导航', '列表'],
  Bell: ['铃铛', '通知', '提醒', '闹钟'],
  Star: ['星星', '收藏', '喜欢', '评分'],
  Heart: ['心', '爱心', '喜欢', '收藏', '爱'],

  // 操作
  Plus: ['加', '增加', '添加', '新建', '创建'],
  Minus: ['减', '减少', '删除', '移除'],
  X: ['关闭', '取消', '叉号', '删除'],
  Check: ['确认', '完成', '对勾', '选中', '正确'],
  Edit: ['编辑', '修改', '铅笔', '更改'],
  Trash: ['删除', '垃圾桶', '移除', '清除'],
  Copy: ['复制', '拷贝', '克隆'],
  Download: ['下载', '保存', '导出'],
  Upload: ['上传', '导入', '发送'],
  Share: ['分享', '转发', '发送'],
  Save: ['保存', '存储', '存档'],
  Printer: ['打印', '打印机'],
  Cut: ['剪切', '裁剪'],
  Paste: ['粘贴'],
  Undo: ['撤销', '回退', '后退'],
  Redo: ['重做', '恢复', '前进'],
  Filter: ['过滤', '筛选', '漏斗'],
  SortAsc: ['升序', '排序', '上升'],
  SortDesc: ['降序', '排序', '下降'],
  RefreshCw: ['刷新', '重载', '更新', '旋转'],
  RotateCw: ['顺时针旋转', '右转'],
  RotateCcw: ['逆时针旋转', '左转'],
  Maximize: ['最大化', '全屏', '放大'],
  Minimize: ['最小化', '缩小'],
  Move: ['移动', '拖动', '位移'],
  Pin: ['固定', '钉住', '置顶'],
  Unpin: ['取消固定', '取消置顶'],

  // 箭头
  ArrowLeft: ['左箭头', '向左', '返回'],
  ArrowRight: ['右箭头', '向右', '前进'],
  ArrowUp: ['上箭头', '向上', '顶部'],
  ArrowDown: ['下箭头', '向下', '底部'],
  ChevronLeft: ['左尖括号', '上一页', '左边'],
  ChevronRight: ['右尖括号', '下一页', '右边'],
  ChevronUp: ['上尖括号', '展开', '向上'],
  ChevronDown: ['下尖括号', '收起', '向下'],

  // 文件
  File: ['文件', '文档'],
  FileText: ['文本文档', '文字文件'],
  Folder: ['文件夹', '目录'],
  FolderOpen: ['打开的文件夹', '展开的目录'],
  Database: ['数据库', '数据', '存储'],
  Server: ['服务器', '主机'],
  Archive: ['归档', '压缩包'],
  Package: ['包裹', '包', '打包'],
  Box: ['盒子', '箱子'],

  // 通讯
  Mail: ['邮件', '邮箱', '信封'],
  MessageSquare: ['消息', '聊天', '对话', '气泡'],
  MessageCircle: ['圆形消息', '评论', '讨论'],
  Send: ['发送', '寄出', '纸飞机'],
  Inbox: ['收件箱', '邮箱'],
  Phone: ['电话', '手机', '通话'],
  Smartphone: ['智能手机', '手机'],
  Tablet: ['平板电脑', '平板'],
  AtSign: ['@符号', '提及', '艾特'],
  ChatBubble: ['聊天气泡', '对话'],
  Comment: ['评论', '留言'],
  Reply: ['回复', '回应'],
  Forward: ['转发', '转寄'],

  // 时间
  Calendar: ['日历', '日程', '日期'],
  Clock: ['时钟', '时间', '钟表'],
  Timer: ['计时器', '定时器'],
  AlarmClock: ['闹钟', '提醒'],
  CalendarDays: ['日历天数', '月份'],
  CalendarCheck: ['日历勾选', '已安排'],
  Hourglass: ['沙漏', '倒计时'],
  Watch: ['手表', '腕表'],

  // 媒体
  Camera: ['相机', '拍照', '摄影'],
  Image: ['图片', '图像', '照片'],
  Video: ['视频', '录像', '影片'],
  Music: ['音乐', '音符', '歌曲'],
  Mic: ['麦克风', '话筒', '录音'],
  Play: ['播放', '开始'],
  Pause: ['暂停', '停止'],
  Stop: ['停止', '结束'],
  Volume2: ['音量', '声音', '喇叭'],
  VolumeX: ['静音', '无声'],
  Headphones: ['耳机', '头戴式'],
  Radio: ['收音机', '广播'],
  Tv: ['电视', '电视机'],
  Monitor: ['显示器', '屏幕', '监视器'],

  // 天气/自然
  Sun: ['太阳', '阳光', '晴天', '白天'],
  Moon: ['月亮', '夜间', '夜晚', '深色模式'],
  Cloud: ['云', '云朵', '阴天'],
  Wind: ['风', '风力', '气流'],
  Rain: ['雨', '下雨', '雨水'],
  Snow: ['雪', '下雪', '雪花'],
  Lightning: ['闪电', '雷电', '雷暴'],
  Thermometer: ['温度计', '体温'],
  Droplets: ['水滴', '湿度', '露珠'],
  Umbrella: ['雨伞', '伞'],
  Flower: ['花', '花朵', '鲜花'],
  Leaf: ['叶子', '树叶', '叶片'],
  Tree: ['树', '树木', '森林'],
  Mountain: ['山', '山脉', '山峰'],
  Waves: ['波浪', '海浪', '水波'],
  Flame: ['火焰', '火', '燃烧'],

  // 位置/地图
  Map: ['地图', '导航图'],
  MapPin: ['地图标记', '位置', '地点', '图钉'],
  Navigation: ['导航', '指南针', '方向'],
  Compass: ['罗盘', '指南针', '方向'],
  Globe: ['地球', '全球', '世界'],
  Location: ['位置', '定位', '地点'],
  Route: ['路线', '路径', '路程'],
  Car: ['汽车', '车', '车辆'],
  Bike: ['自行车', '单车'],
  Train: ['火车', '列车'],
  Plane: ['飞机', '航空', '航班'],
  Ship: ['船', '轮船', '船舶'],

  // 安全
  Lock: ['锁', '锁定', '加密', '安全'],
  Unlock: ['解锁', '开锁', '解密'],
  Shield: ['盾牌', '保护', '防护', '安全'],
  ShieldCheck: ['安全检查', '已保护'],
  Key: ['钥匙', '密钥', '密码'],
  Eye: ['眼睛', '查看', '可见'],
  EyeOff: ['隐藏', '不可见', '闭眼'],
  Fingerprint: ['指纹', '生物识别'],
  AlertTriangle: ['警告', '危险', '注意', '三角形'],
  AlertCircle: ['警告圆圈', '错误', '提示'],
  Info: ['信息', '详情', '说明'],
  HelpCircle: ['帮助', '问号', '疑问'],

  // 布局
  Grid: ['网格', '格子', '布局'],
  List: ['列表', '清单'],
  Columns: ['列', '分栏', '多列'],
  Rows: ['行', '分行'],
  Layout: ['布局', '排版'],
  Panel: ['面板', '侧边栏'],
  Sidebar: ['侧边栏', '边栏'],
  Window: ['窗口', '视窗'],
  Split: ['分割', '分开'],
  AlignLeft: ['左对齐'],
  AlignRight: ['右对齐'],
  AlignCenter: ['居中对齐'],
  Justify: ['两端对齐'],

  // 形状
  Circle: ['圆形', '圆圈'],
  Square: ['正方形', '方形'],
  Triangle: ['三角形', '三角'],
  Hexagon: ['六边形'],
  Diamond: ['菱形', '钻石'],
  Rectangle: ['矩形', '长方形'],
  Pentagon: ['五边形'],
  Octagon: ['八边形'],
  CircleDot: ['圆点', '靶心'],
  SquareDot: ['方点'],
  Bookmark: ['书签', '标记'],
  Tag: ['标签', 'tag'],
  Tags: ['多个标签'],
  Hash: ['井号', 'hashtag', '标签'],

  // 图表/数据
  BarChart: ['柱状图', '条形图', '图表'],
  PieChart: ['饼图', '扇形图'],
  LineChart: ['折线图', '趋势图'],
  TrendingUp: ['上升趋势', '增长'],
  TrendingDown: ['下降趋势', '减少'],
  Activity: ['活动', '动态', '脉搏'],
  Target: ['目标', '靶子', '指标'],
  Award: ['奖项', '成就', '奖杯'],
  Trophy: ['奖杯', '冠军', '胜利'],
  Medal: ['奖牌', '勋章'],
  Crown: ['皇冠', '王冠', '王者'],
  Zap: ['闪电', '能量', '快速'],
  Sparkles: ['闪光', '火花', '特效'],

  // 购物/金钱
  ShoppingCart: ['购物车', '购买'],
  ShoppingBag: ['购物袋', '袋子'],
  CreditCard: ['信用卡', '银行卡', '支付'],
  DollarSign: ['美元', '金钱', '货币'],
  Wallet: ['钱包', '钱夹'],
  Banknote: ['钞票', '纸币'],
  Coins: ['硬币', '金币'],
  Receipt: ['收据', '发票', '小票'],
  Gift: ['礼物', '礼品', '赠品'],
  Percent: ['百分比', '折扣', '优惠'],
  Store: ['商店', '店铺', '商城'],

  // 社交
  ThumbsUp: ['点赞', '喜欢', '拇指向上'],
  ThumbsDown: ['踩', '不喜欢', '拇指向下'],
  Smile: ['微笑', '笑脸', '开心'],
  Frown: ['皱眉', '不开心', '难过'],
  Meh: ['面无表情', '一般'],
  Laugh: ['大笑', '哈哈'],
  Angry: ['生气', '愤怒'],
  Surprised: ['惊讶', '吃惊'],
  Wink: ['眨眼', '调皮'],
  Tongue: ['吐舌头', '调皮'],

  // 系统/工具
  Cpu: ['处理器', 'CPU', '芯片'],
  HardDrive: ['硬盘', '存储'],
  MemoryStick: ['内存条', 'RAM'],
  Battery: ['电池', '电量'],
  Power: ['电源', '开关', '电力'],
  Wifi: ['无线网络', 'WiFi', '信号'],
  Bluetooth: ['蓝牙'],
  Usb: ['USB', '接口'],
  Terminal: ['终端', '命令行', '控制台'],
  Code: ['代码', '编程', '程序员'],
  GitBranch: ['分支', 'git', '版本控制'],
  GitCommit: ['提交', 'git commit'],
  GitMerge: ['合并', 'git merge'],
  Github: ['GitHub', '代码托管'],

  // 设备
  Laptop: ['笔记本电脑', '笔记本'],
  Desktop: ['台式电脑', '台式机'],
  Webcam: ['摄像头', '网络摄像头'],
  Microphone: ['麦克风', '话筒'],
  Speaker: ['扬声器', '音箱'],

  // 食物
  Apple: ['苹果', '水果'],
  Coffee: ['咖啡', '饮品'],
  Wine: ['葡萄酒', '红酒', '酒'],
  Pizza: ['披萨', '比萨'],
  Sandwich: ['三明治'],
  IceCream: ['冰淇淋', '雪糕'],
  Cake: ['蛋糕', '甜点'],
  Cookie: ['饼干', '曲奇'],
  Candy: ['糖果', '甜品'],
  Cherry: ['樱桃', '车厘子'],
  Lemon: ['柠檬', '柑橘'],
  Peach: ['桃子'],
  Banana: ['香蕉'],
  Carrot: ['胡萝卜', '蔬菜'],
  Corn: ['玉米'],
  Egg: ['鸡蛋', '蛋'],
  Fish: ['鱼', '鱼类'],
  Meat: ['肉', '肉类'],
  Drumstick: ['鸡腿', '禽肉'],
  Croissant: ['羊角面包', '可颂'],

  // 医疗
  Stethoscope: ['听诊器', '医生'],
  Syringe: ['注射器', '针筒', '疫苗'],
  Pill: ['药丸', '药物', '胶囊'],
  Bandage: ['绷带', '创可贴'],
  HeartPulse: ['心跳', '心率', '脉搏'],
  Ambulance: ['救护车'],
  Hospital: ['医院'],
  Dna: ['DNA', '基因', '遗传'],
  Brain: ['大脑', '脑部', '智力'],
  Bone: ['骨头', '骨骼'],
  Tooth: ['牙齿', '牙医'],

  // 运动
  Dumbbell: ['哑铃', '健身', '锻炼'],
  Running: ['跑步', '奔跑'],
  Walking: ['走路', '步行'],
  Cycling: ['骑行', '骑自行车'],
  Swimming: ['游泳'],
  Basketball: ['篮球'],
  Football: ['足球'],
  Baseball: ['棒球'],
  Tennis: ['网球'],
  Golf: ['高尔夫'],
  Boxing: ['拳击'],
  Yoga: ['瑜伽'],
  Whistle: ['哨子', '裁判'],

  // 游戏
  Gamepad: ['游戏手柄', '控制器'],
  Joystick: ['操纵杆', '摇杆'],
  Dice: ['骰子', '色子'],
  Puzzle: ['拼图', '益智'],
  Chess: ['国际象棋', '棋子'],
  Cards: ['扑克牌', '卡片'],
  Ghost: ['幽灵', '鬼魂'],
  Skull: ['骷髅', '头骨'],
  Sword: ['剑', '武器'],
  Wand: ['魔杖', '魔法棒'],
  Potion: ['药水', '药剂'],
  Gem: ['宝石', '钻石'],

  // 建筑
  Building: ['建筑物', '大楼'],
  Building2: ['办公楼', '写字楼'],
  House: ['房子', '住宅', '房屋'],
  School: ['学校', '学院'],
  Church: ['教堂', '教会'],
  Castle: ['城堡'],
  Factory: ['工厂', '厂房'],
  Warehouse: ['仓库', '仓储'],
  Hotel: ['酒店', '宾馆'],
  Tent: ['帐篷', '露营'],
  Bridge: ['桥梁', '桥'],
  Tower: ['塔', '塔楼'],
  Lighthouse: ['灯塔'],

  // 科学
  Flask: ['烧瓶', '实验', '化学'],
  Beaker: ['烧杯', '量杯'],
  TestTube: ['试管'],
  Atom: ['原子', '分子', '科学'],
  Magnet: ['磁铁', '磁性'],
  Telescope: ['望远镜', '天文'],
  Microscope: ['显微镜'],
  Satellite: ['卫星'],
  Rocket: ['火箭', '航天'],
  Orbit: ['轨道', '环绕'],
  Planet: ['行星', '星球'],
  Stars: ['星星', '星空'],
  Meteor: ['流星', '陨石'],
  Comet: ['彗星'],
  Eclipse: ['日食', '月食'],
  Radiation: ['辐射', '放射性'],
  Biohazard: ['生物危害', '危险'],

  // 摄影
  Aperture: ['光圈', '相机'],
  Focus: ['对焦', '焦点'],
  ZoomIn: ['放大', '拉近'],
  ZoomOut: ['缩小', '拉远'],
  Crop: ['裁剪', '裁切'],
  Rotate: ['旋转'],
  FlipHorizontal: ['水平翻转'],
  FlipVertical: ['垂直翻转'],
  Contrast: ['对比度'],
  Brightness: ['亮度'],
  Saturation: ['饱和度'],
  Hue: ['色调'],
  Palette: ['调色板', '颜色'],
  Paintbrush: ['画笔', '刷子'],
  Eraser: ['橡皮擦', '橡皮'],
  Pencil: ['铅笔'],
  Pen: ['钢笔', '笔'],
  Marker: ['马克笔', '记号笔'],
  Highlighter: ['荧光笔'],
  Ruler: ['尺子', '直尺'],
  Scissors: ['剪刀'],
  Tape: ['胶带', '透明胶'],
  Glue: ['胶水', '粘合剂'],
  Stamp: ['印章', '邮戳'],
  Frame: ['相框', '框架'],
  Picture: ['图片', '照片'],
  Slideshow: ['幻灯片', '演示'],
  Film: ['胶片', '电影'],
  Clapperboard: ['场记板', '拍板'],
  Megaphone: ['扩音器', '喇叭'],
  Bullhorn: ['号角', '宣传'],
}

// 按分类组织的图标 (基于 Lucide 官方分类,已去重)
const iconsByCategory: Record<IconCategory, string[]> = {
  all: [], // 将在下面填充

  accessibility: [
    ICON_POOL.Ear,
    ICON_POOL.Eye,
    ICON_POOL.EyeOff,
    ICON_POOL.Hand,
    ICON_POOL.Wheelchair,
    ICON_POOL.Braille,
    ICON_POOL.Accessibility,
    ICON_POOL.UniversalAccess,
    ICON_POOL.HearingAid,
  ],

  account: [
    ICON_POOL.User,
    ICON_POOL.Users,
    ICON_POOL.UserPlus,
    ICON_POOL.UserMinus,
    ICON_POOL.UserCheck,
    ICON_POOL.UserX,
    ICON_POOL.UserCog,
    ICON_POOL.UserRound,
    ICON_POOL.UserRoundPlus,
    ICON_POOL.UserRoundX,
    ICON_POOL.Contact,
    ICON_POOL.Contacts,
    ICON_POOL.PersonStanding,
    ICON_POOL.Baby,
    ICON_POOL.Child,
  ],

  animals: [
    ICON_POOL.Dog,
    ICON_POOL.Cat,
    ICON_POOL.Fish,
    ICON_POOL.Bird,
    ICON_POOL.Rabbit,
    ICON_POOL.Turtle,
    ICON_POOL.Bug,
    ICON_POOL.Snail,
    ICON_POOL.Spider,
    ICON_POOL.Bear,
    ICON_POOL.Wolf,
    ICON_POOL.Fox,
    ICON_POOL.Horse,
    ICON_POOL.Cow,
    ICON_POOL.Pig,
    ICON_POOL.Sheep,
    ICON_POOL.Chicken,
    ICON_POOL.Rooster,
  ],

  arrows: [
    ICON_POOL.ArrowLeft,
    ICON_POOL.ArrowRight,
    ICON_POOL.ArrowUp,
    ICON_POOL.ArrowDown,
    ICON_POOL.ArrowLeftRight,
    ICON_POOL.ArrowUpDown,
    ICON_POOL.ArrowUpLeft,
    ICON_POOL.ArrowUpRight,
    ICON_POOL.ArrowDownLeft,
    ICON_POOL.ArrowDownRight,
    ICON_POOL.ArrowLeftFromLine,
    ICON_POOL.ArrowRightFromLine,
    ICON_POOL.ChevronLeft,
    ICON_POOL.ChevronRight,
    ICON_POOL.ChevronUp,
    ICON_POOL.ChevronDown,
    ICON_POOL.ChevronsLeft,
    ICON_POOL.ChevronsRight,
    ICON_POOL.ChevronsUp,
    ICON_POOL.ChevronsDown,
    ICON_POOL.CornerDownLeft,
    ICON_POOL.CornerDownRight,
    ICON_POOL.CornerUpLeft,
    ICON_POOL.CornerUpRight,
  ],

  brands: [
    ICON_POOL.Github,
    ICON_POOL.Gitlab,
    ICON_POOL.Bitbucket,
    ICON_POOL.Chrome,
    ICON_POOL.Firefox,
    ICON_POOL.Safari,
    ICON_POOL.Apple,
    ICON_POOL.Android,
    ICON_POOL.Windows,
    ICON_POOL.Linux,
    ICON_POOL.Facebook,
    ICON_POOL.Instagram,
    ICON_POOL.Twitter,
    ICON_POOL.Linkedin,
    ICON_POOL.Youtube,
    ICON_POOL.Tiktok,
    ICON_POOL.Snapchat,
    ICON_POOL.Pinterest,
    ICON_POOL.Reddit,
    ICON_POOL.Discord,
    ICON_POOL.Slack,
    ICON_POOL.Telegram,
    ICON_POOL.WhatsApp,
    ICON_POOL.Wechat,
    ICON_POOL.QQ,
    ICON_POOL.Dribbble,
    ICON_POOL.Behance,
    ICON_POOL.Figma,
    ICON_POOL.Sketch,
    ICON_POOL.Adobe,
  ],

  buildings: [
    ICON_POOL.Building,
    ICON_POOL.Building2,
    ICON_POOL.House,
    ICON_POOL.Hotel,
    ICON_POOL.Hospital,
    ICON_POOL.School,
    ICON_POOL.University,
    ICON_POOL.Store,
    ICON_POOL.Shop,
    ICON_POOL.Warehouse,
    ICON_POOL.Factory,
    ICON_POOL.Church,
    ICON_POOL.Temple,
    ICON_POOL.Castle,
    ICON_POOL.Tower,
  ],

  charts: [
    ICON_POOL.BarChart,
    ICON_POOL.BarChartHorizontal,
    ICON_POOL.BarChartBig,
    ICON_POOL.LineChart,
    ICON_POOL.AreaChart,
    ICON_POOL.PieChart,
    ICON_POOL.Donut,
    ICON_POOL.TrendingUp,
    ICON_POOL.TrendingDown,
    ICON_POOL.Activity,
    ICON_POOL.ChartBar,
    ICON_POOL.ChartLine,
    ICON_POOL.ChartPie,
    ICON_POOL.ChartArea,
    ICON_POOL.ChartScatter,
  ],

  communication: [
    ICON_POOL.MessageSquare,
    ICON_POOL.MessageCircle,
    ICON_POOL.ChatBubble,
    ICON_POOL.Comment,
    ICON_POOL.Send,
    ICON_POOL.Inbox,
    ICON_POOL.Outbox,
    ICON_POOL.Reply,
    ICON_POOL.ReplyAll,
    ICON_POOL.Forward,
    ICON_POOL.Mention,
    ICON_POOL.Quote,
    ICON_POOL.Hash,
    ICON_POOL.AtSign,
  ],

  connectivity: [
    ICON_POOL.Wifi,
    ICON_POOL.WifiOff,
    ICON_POOL.Bluetooth,
    ICON_POOL.BluetoothConnected,
    ICON_POOL.BluetoothSearching,
    ICON_POOL.Signal,
    ICON_POOL.SignalHigh,
    ICON_POOL.SignalMedium,
    ICON_POOL.SignalLow,
    ICON_POOL.SignalZero,
    ICON_POOL.Radio,
    ICON_POOL.Rss,
    ICON_POOL.Nfc,
    ICON_POOL.Usb,
    ICON_POOL.Hdmi,
  ],

  cursors: [
    ICON_POOL.MousePointer,
    ICON_POOL.MousePointerClick,
    ICON_POOL.MousePointer2,
    ICON_POOL.Cursor,
    ICON_POOL.Move,
    ICON_POOL.Hand,
    ICON_POOL.Grab,
    ICON_POOL.Pin,
    ICON_POOL.Unpin,
  ],

  design: [
    ICON_POOL.Palette,
    ICON_POOL.Paintbrush,
    ICON_POOL.PaintBucket,
    ICON_POOL.Eraser,
    ICON_POOL.Pen,
    ICON_POOL.Pencil,
    ICON_POOL.PenTool,
    ICON_POOL.Vector,
    ICON_POOL.BezierCurve,
    ICON_POOL.Crop,
    ICON_POOL.RotateCw,
    ICON_POOL.RotateCcw,
    ICON_POOL.FlipHorizontal,
    ICON_POOL.FlipVertical,
    ICON_POOL.Scale,
    ICON_POOL.Resize,
  ],

  development: [
    ICON_POOL.Code,
    ICON_POOL.Code2,
    ICON_POOL.Terminal,
    ICON_POOL.Command,
    ICON_POOL.Console,
    ICON_POOL.FileCode,
    ICON_POOL.FileType,
    ICON_POOL.Braces,
    ICON_POOL.Brackets,
    ICON_POOL.Parentheses,
    ICON_POOL.Bug,
    ICON_POOL.GitBranch,
    ICON_POOL.GitCommit,
    ICON_POOL.GitMerge,
    ICON_POOL.GitPullRequest,
    ICON_POOL.Database,
    ICON_POOL.Server,
    ICON_POOL.Cloud,
    ICON_POOL.Api,
  ],

  devices: [
    ICON_POOL.Smartphone,
    ICON_POOL.Tablet,
    ICON_POOL.Laptop,
    ICON_POOL.Monitor,
    ICON_POOL.Tv,
    ICON_POOL.Speaker,
    ICON_POOL.Headphones,
    ICON_POOL.Camera,
    ICON_POOL.Printer,
    ICON_POOL.Scanner,
    ICON_POOL.Projector,
    ICON_POOL.Watch,
    ICON_POOL.Clock,
    ICON_POOL.AlarmClock,
    ICON_POOL.Timer,
  ],

  emoji: [
    ICON_POOL.Smile,
    ICON_POOL.Frown,
    ICON_POOL.Meh,
    ICON_POOL.Laugh,
    ICON_POOL.Angry,
    ICON_POOL.Surprised,
    ICON_POOL.ThumbsUp,
    ICON_POOL.ThumbsDown,
    ICON_POOL.Heart,
    ICON_POOL.Star,
    ICON_POOL.Sparkles,
  ],

  files: [
    ICON_POOL.File,
    ICON_POOL.Files,
    ICON_POOL.Folder,
    ICON_POOL.Folders,
    ICON_POOL.FolderOpen,
    ICON_POOL.FolderTree,
    ICON_POOL.FileText,
    ICON_POOL.FileCode,
    ICON_POOL.FileJson,
    ICON_POOL.FileImage,
    ICON_POOL.FileVideo,
    ICON_POOL.FileAudio,
    ICON_POOL.FileZip,
    ICON_POOL.FileSpreadsheet,
    ICON_POOL.FilePresentation,
    ICON_POOL.FileDocument,
    ICON_POOL.Archive,
    ICON_POOL.Package,
    ICON_POOL.Box,
    ICON_POOL.HardDrive,
  ],

  food: [
    ICON_POOL.Coffee,
    ICON_POOL.CupSoda,
    ICON_POOL.Wine,
    ICON_POOL.Beer,
    ICON_POOL.Martini,
    ICON_POOL.Pizza,
    ICON_POOL.Sandwich,
    ICON_POOL.Utensils,
    ICON_POOL.ChefHat,
    ICON_POOL.IceCream,
    ICON_POOL.Cake,
    ICON_POOL.Candy,
    ICON_POOL.Apple,
    ICON_POOL.Carrot,
    ICON_POOL.Corn,
  ],

  gaming: [
    ICON_POOL.Gamepad,
    ICON_POOL.Gamepad2,
    ICON_POOL.Joystick,
    ICON_POOL.Dice,
    ICON_POOL.Cards,
    ICON_POOL.Trophy,
    ICON_POOL.Medal,
    ICON_POOL.Award,
    ICON_POOL.Target,
    ICON_POOL.Crosshair,
    ICON_POOL.Sword,
    ICON_POOL.Shield,
    ICON_POOL.Helmet,
    ICON_POOL.Bow,
    ICON_POOL.Wand,
  ],

  home: [
    ICON_POOL.Home,
    ICON_POOL.Bed,
    ICON_POOL.Chair,
    ICON_POOL.Couch,
    ICON_POOL.Lamp,
    ICON_POOL.Refrigerator,
    ICON_POOL.Microwave,
    ICON_POOL.Oven,
    ICON_POOL.WashingMachine,
    ICON_POOL.Bath,
    ICON_POOL.Shower,
    ICON_POOL.Toilet,
    ICON_POOL.Sink,
    ICON_POOL.Door,
    ICON_POOL.Window,
  ],

  layout: [
    ICON_POOL.Layout,
    ICON_POOL.LayoutGrid,
    ICON_POOL.LayoutList,
    ICON_POOL.LayoutPanelLeft,
    ICON_POOL.LayoutPanelTop,
    ICON_POOL.LayoutPanelBottom,
    ICON_POOL.Sidebar,
    ICON_POOL.SidebarClose,
    ICON_POOL.SidebarOpen,
    ICON_POOL.Columns,
    ICON_POOL.Rows,
    ICON_POOL.Split,
    ICON_POOL.Combine,
    ICON_POOL.Overlap,
    ICON_POOL.Stack,
    ICON_POOL.AlignStartHorizontal,
    ICON_POOL.AlignEndHorizontal,
    ICON_POOL.AlignCenterHorizontal,
    ICON_POOL.AlignStartVertical,
    ICON_POOL.AlignEndVertical,
    ICON_POOL.AlignCenterVertical,
  ],

  mail: [
    ICON_POOL.Mail,
    ICON_POOL.MailOpen,
    ICON_POOL.MailCheck,
    ICON_POOL.MailPlus,
    ICON_POOL.MailSearch,
    ICON_POOL.MailWarning,
    ICON_POOL.MailQuestion,
    ICON_POOL.MailX,
    ICON_POOL.Inbox,
    ICON_POOL.Outbox,
    ICON_POOL.Send,
  ],

  maps: [
    ICON_POOL.Map,
    ICON_POOL.MapPin,
    ICON_POOL.MapPinned,
    ICON_POOL.Navigation,
    ICON_POOL.Navigation2,
    ICON_POOL.Compass,
    ICON_POOL.Globe,
    ICON_POOL.Locate,
    ICON_POOL.LocateFixed,
    ICON_POOL.Route,
    ICON_POOL.Signpost,
    ICON_POOL.Mountain,
    ICON_POOL.Trees,
    ICON_POOL.Landmark,
    ICON_POOL.Flag,
  ],

  math: [
    ICON_POOL.Plus,
    ICON_POOL.Minus,
    ICON_POOL.Multiply,
    ICON_POOL.Divide,
    ICON_POOL.Equal,
    ICON_POOL.NotEqual,
    ICON_POOL.GreaterThan,
    ICON_POOL.LessThan,
    ICON_POOL.Percent,
    ICON_POOL.Hash,
    ICON_POOL.Infinity,
    ICON_POOL.Pi,
    ICON_POOL.Sigma,
    ICON_POOL.Function,
    ICON_POOL.Calculator,
  ],

  medical: [
    ICON_POOL.HeartPulse,
    ICON_POOL.Stethoscope,
    ICON_POOL.Pill,
    ICON_POOL.Syringe,
    ICON_POOL.Bandage,
    ICON_POOL.Ambulance,
    ICON_POOL.Hospital,
    ICON_POOL.Clinic,
    ICON_POOL.MedicalCross,
    ICON_POOL.Brain,
    ICON_POOL.Bone,
    ICON_POOL.Lungs,
    ICON_POOL.Kidneys,
    ICON_POOL.Dna,
  ],

  money: [
    ICON_POOL.DollarSign,
    ICON_POOL.Euro,
    ICON_POOL.PoundSterling,
    ICON_POOL.Yen,
    ICON_POOL.Bitcoin,
    ICON_POOL.Ethereum,
    ICON_POOL.CreditCard,
    ICON_POOL.Wallet,
    ICON_POOL.Banknote,
    ICON_POOL.Coins,
    ICON_POOL.Receipt,
    ICON_POOL.ShoppingCart,
    ICON_POOL.ShoppingBag,
    ICON_POOL.Basket,
    ICON_POOL.Tag,
    ICON_POOL.Tags,
  ],

  music: [
    ICON_POOL.Music,
    ICON_POOL.Music2,
    ICON_POOL.Music3,
    ICON_POOL.Music4,
    ICON_POOL.Mic,
    ICON_POOL.Mic2,
    ICON_POOL.Headphones,
    ICON_POOL.Speaker,
    ICON_POOL.Volume,
    ICON_POOL.Volume1,
    ICON_POOL.Volume2,
    ICON_POOL.VolumeX,
    ICON_POOL.Play,
    ICON_POOL.Pause,
    ICON_POOL.Stop,
    ICON_POOL.SkipBack,
    ICON_POOL.SkipForward,
    ICON_POOL.Rewind,
    ICON_POOL.FastForward,
    ICON_POOL.Radio,
    ICON_POOL.Podcast,
    ICON_POOL.Disc,
    ICON_POOL.Vinyl,
    ICON_POOL.Tape,
  ],

  nature: [
    ICON_POOL.Sun,
    ICON_POOL.Moon,
    ICON_POOL.Star,
    ICON_POOL.Cloud,
    ICON_POOL.Wind,
    ICON_POOL.Rain,
    ICON_POOL.Snow,
    ICON_POOL.Snowflake,
    ICON_POOL.Flower,
    ICON_POOL.Leaf,
    ICON_POOL.Tree,
    ICON_POOL.Trees,
    ICON_POOL.Forest,
    ICON_POOL.Mountain,
    ICON_POOL.Waves,
    ICON_POOL.Droplets,
    ICON_POOL.Flame,
    ICON_POOL.Zap,
    ICON_POOL.Umbrella,
  ],

  navigation: [
    ICON_POOL.Navigation,
    ICON_POOL.Navigation2,
    ICON_POOL.Compass,
    ICON_POOL.Map,
    ICON_POOL.Globe,
    ICON_POOL.Menu,
    ICON_POOL.MoreHorizontal,
    ICON_POOL.MoreVertical,
  ],

  notifications: [
    ICON_POOL.Bell,
    ICON_POOL.BellRing,
    ICON_POOL.BellOff,
    ICON_POOL.BellPlus,
    ICON_POOL.BellMinus,
    ICON_POOL.AlertCircle,
    ICON_POOL.AlertTriangle,
    ICON_POOL.AlertOctagon,
    ICON_POOL.Info,
    ICON_POOL.HelpCircle,
    ICON_POOL.Notification,
  ],

  people: [
    ICON_POOL.User,
    ICON_POOL.Users,
    ICON_POOL.UserPlus,
    ICON_POOL.UserMinus,
    ICON_POOL.UserCheck,
    ICON_POOL.UserX,
    ICON_POOL.PersonStanding,
    ICON_POOL.Baby,
    ICON_POOL.Child,
    ICON_POOL.Adult,
    ICON_POOL.Senior,
    ICON_POOL.UsersRound,
    ICON_POOL.UserRound,
    ICON_POOL.UserRoundPlus,
    ICON_POOL.UserRoundX,
  ],

  photography: [
    ICON_POOL.Camera,
    ICON_POOL.CameraOff,
    ICON_POOL.Image,
    ICON_POOL.Images,
    ICON_POOL.Photo,
    ICON_POOL.Photos,
    ICON_POOL.Aperture,
    ICON_POOL.Focus,
    ICON_POOL.ZoomIn,
    ICON_POOL.ZoomOut,
    ICON_POOL.Flashlight,
    ICON_POOL.Film,
    ICON_POOL.Video,
    ICON_POOL.VideoOff,
    ICON_POOL.Clapperboard,
  ],

  science: [
    ICON_POOL.Atom,
    ICON_POOL.Dna,
    ICON_POOL.Microscope,
    ICON_POOL.Telescope,
    ICON_POOL.TestTube,
    ICON_POOL.Beaker,
    ICON_POOL.Flask,
    ICON_POOL.Magnet,
    ICON_POOL.Radiation,
    ICON_POOL.Biohazard,
    ICON_POOL.Virus,
    ICON_POOL.Rocket,
    ICON_POOL.Satellite,
    ICON_POOL.Orbit,
    ICON_POOL.Planet,
  ],

  security: [
    ICON_POOL.Lock,
    ICON_POOL.Unlock,
    ICON_POOL.Key,
    ICON_POOL.Shield,
    ICON_POOL.ShieldCheck,
    ICON_POOL.ShieldAlert,
    ICON_POOL.ShieldX,
    ICON_POOL.Eye,
    ICON_POOL.EyeOff,
    ICON_POOL.Scan,
    ICON_POOL.Fingerprint,
    ICON_POOL.FaceId,
    ICON_POOL.Password,
    ICON_POOL.Verified,
    ICON_POOL.Unverified,
    ICON_POOL.Ban,
    ICON_POOL.NoEntry,
    ICON_POOL.CheckCircle,
    ICON_POOL.XCircle,
  ],

  shapes: [
    ICON_POOL.Circle,
    ICON_POOL.Square,
    ICON_POOL.Triangle,
    ICON_POOL.Hexagon,
    ICON_POOL.Octagon,
    ICON_POOL.Diamond,
    ICON_POOL.Rectangle,
    ICON_POOL.Pentagon,
    ICON_POOL.Bookmark,
    ICON_POOL.CircleDot,
    ICON_POOL.SquareDot,
    ICON_POOL.TriangleRight,
    ICON_POOL.Slash,
    ICON_POOL.Backslash,
  ],

  shopping: [
    ICON_POOL.ShoppingCart,
    ICON_POOL.ShoppingBag,
    ICON_POOL.Basket,
    ICON_POOL.Store,
    ICON_POOL.Shop,
    ICON_POOL.Market,
    ICON_POOL.CreditCard,
    ICON_POOL.Wallet,
    ICON_POOL.Banknote,
    ICON_POOL.Coins,
    ICON_POOL.DollarSign,
    ICON_POOL.Tag,
    ICON_POOL.Tags,
    ICON_POOL.Gift,
    ICON_POOL.Receipt,
    ICON_POOL.Barcode,
    ICON_POOL.QrCode,
    ICON_POOL.Truck,
    ICON_POOL.Package,
    ICON_POOL.Box,
    ICON_POOL.Percent,
    ICON_POOL.Sale,
  ],

  social: [
    ICON_POOL.ThumbsUp,
    ICON_POOL.ThumbsDown,
    ICON_POOL.Heart,
    ICON_POOL.Share,
    ICON_POOL.Share2,
    ICON_POOL.MessageSquare,
    ICON_POOL.MessageCircle,
    ICON_POOL.ChatBubble,
    ICON_POOL.Comment,
    ICON_POOL.Users,
    ICON_POOL.UserPlus,
    ICON_POOL.UserMinus,
    ICON_POOL.Contact,
    ICON_POOL.Contacts,
    ICON_POOL.Handshake,
    ICON_POOL.Hand,
    ICON_POOL.Fist,
    ICON_POOL.Peace,
    ICON_POOL.RockOn,
  ],

  sports: [
    ICON_POOL.Football,
    ICON_POOL.Basketball,
    ICON_POOL.Baseball,
    ICON_POOL.Soccer,
    ICON_POOL.Tennis,
    ICON_POOL.Golf,
    ICON_POOL.Hockey,
    ICON_POOL.Cricket,
    ICON_POOL.Rugby,
    ICON_POOL.Volleyball,
    ICON_POOL.Badminton,
    ICON_POOL.Trophy,
    ICON_POOL.Medal,
    ICON_POOL.Award,
    ICON_POOL.Target,
    ICON_POOL.Dumbbell,
    ICON_POOL.Weights,
  ],

  sustainability: [
    ICON_POOL.Recycle,
    ICON_POOL.Leaf,
    ICON_POOL.Tree,
    ICON_POOL.Trees,
    ICON_POOL.Forest,
    ICON_POOL.Sprout,
    ICON_POOL.SolarPanel,
    ICON_POOL.Wind,
    ICON_POOL.Water,
    ICON_POOL.Droplets,
    ICON_POOL.Waves,
    ICON_POOL.Earth,
    ICON_POOL.Globe,
    ICON_POOL.Seedling,
    ICON_POOL.Compost,
  ],

  text: [
    ICON_POOL.Type,
    ICON_POOL.Text,
    ICON_POOL.TextSelect,
    ICON_POOL.TextCursor,
    ICON_POOL.TextQuote,
    ICON_POOL.Bold,
    ICON_POOL.Italic,
    ICON_POOL.Underline,
    ICON_POOL.Strikethrough,
    ICON_POOL.AlignLeft,
    ICON_POOL.AlignCenter,
    ICON_POOL.AlignRight,
    ICON_POOL.AlignJustify,
    ICON_POOL.List,
    ICON_POOL.ListOrdered,
    ICON_POOL.Indent,
    ICON_POOL.Outdent,
    ICON_POOL.Superscript,
    ICON_POOL.Subscript,
  ],

  time: [
    ICON_POOL.Clock,
    ICON_POOL.Clock1,
    ICON_POOL.Clock2,
    ICON_POOL.Clock3,
    ICON_POOL.Clock4,
    ICON_POOL.Clock5,
    ICON_POOL.Clock6,
    ICON_POOL.Clock7,
    ICON_POOL.Clock8,
    ICON_POOL.Clock9,
    ICON_POOL.Clock10,
    ICON_POOL.Clock11,
    ICON_POOL.Clock12,
    ICON_POOL.Calendar,
    ICON_POOL.CalendarDays,
    ICON_POOL.CalendarCheck,
    ICON_POOL.CalendarX,
    ICON_POOL.CalendarPlus,
    ICON_POOL.Hourglass,
    ICON_POOL.Watch,
    ICON_POOL.Stopwatch,
    ICON_POOL.Timer,
    ICON_POOL.History,
    ICON_POOL.Sunrise,
    ICON_POOL.Sunset,
    ICON_POOL.Moon,
    ICON_POOL.Sun,
  ],

  tools: [
    ICON_POOL.Settings,
    ICON_POOL.Tool,
    ICON_POOL.Hammer,
    ICON_POOL.Wrench,
    ICON_POOL.Screwdriver,
    ICON_POOL.Pliers,
    ICON_POOL.Ruler,
    ICON_POOL.Scissors,
    ICON_POOL.Paperclip,
    ICON_POOL.Pushpin,
    ICON_POOL.Pin,
    ICON_POOL.Unpin,
    ICON_POOL.Save,
    ICON_POOL.Download,
    ICON_POOL.Upload,
    ICON_POOL.Copy,
    ICON_POOL.Paste,
    ICON_POOL.Cut,
    ICON_POOL.Undo,
    ICON_POOL.Redo,
    ICON_POOL.RefreshCw,
    ICON_POOL.RotateCw,
    ICON_POOL.RotateCcw,
  ],

  transportation: [
    ICON_POOL.Car,
    ICON_POOL.Truck,
    ICON_POOL.Bus,
    ICON_POOL.Train,
    ICON_POOL.Plane,
    ICON_POOL.Ship,
    ICON_POOL.Boat,
    ICON_POOL.Bike,
    ICON_POOL.Motorcycle,
    ICON_POOL.Scooter,
    ICON_POOL.Skateboard,
    ICON_POOL.Wheelchair,
    ICON_POOL.Fuel,
    ICON_POOL.GasStation,
    ICON_POOL.ParkingMeter,
    ICON_POOL.TrafficCone,
  ],

  travel: [
    ICON_POOL.Plane,
    ICON_POOL.Train,
    ICON_POOL.Bus,
    ICON_POOL.Car,
    ICON_POOL.Bike,
    ICON_POOL.Ship,
    ICON_POOL.Boat,
    ICON_POOL.Suitcase,
    ICON_POOL.Backpack,
    ICON_POOL.Passport,
    ICON_POOL.Ticket,
    ICON_POOL.Visa,
    ICON_POOL.Hotel,
    ICON_POOL.Restaurant,
    ICON_POOL.Coffee,
    ICON_POOL.Map,
    ICON_POOL.Compass,
    ICON_POOL.Globe,
  ],

  weather: [
    ICON_POOL.Sun,
    ICON_POOL.Moon,
    ICON_POOL.Cloud,
    ICON_POOL.CloudRain,
    ICON_POOL.CloudSnow,
    ICON_POOL.CloudLightning,
    ICON_POOL.CloudDrizzle,
    ICON_POOL.CloudFog,
    ICON_POOL.CloudHail,
    ICON_POOL.CloudSun,
    ICON_POOL.CloudMoon,
    ICON_POOL.Wind,
    ICON_POOL.Rain,
    ICON_POOL.Snow,
    ICON_POOL.Snowflake,
    ICON_POOL.Zap,
    ICON_POOL.Thunderstorm,
    ICON_POOL.Thermometer,
    ICON_POOL.ThermometerSun,
    ICON_POOL.ThermometerSnowflake,
    ICON_POOL.Umbrella,
    ICON_POOL.Waves,
    ICON_POOL.Droplets,
    ICON_POOL.Flame,
    ICON_POOL.Tornado,
  ],
}

// 填充 "all" 分类(自动去重)
iconsByCategory.all = [...new Set(Object.values(iconsByCategory).flat())]

// 根据图标名称获取分类
export interface IconItem {
  name: string
  icon: unknown
  category: IconCategory | 'other'
  chineseKeywords: string[]
}

// 生成图标列表(带分类信息和中文关键词)
export const iconList: IconItem[] = iconsByCategory.all
  .map((name) => ({
    name,
    icon: (LucideIcons as Record<string, unknown>)[name],
    category: getCategoryByName(name),
    chineseKeywords: iconChineseNames[name] || [],
  }))
  .filter((item) => item.icon)

// 根据图标名称获取分类
function getCategoryByName(name: string): IconCategory | 'other' {
  for (const [category, icons] of Object.entries(iconsByCategory)) {
    if (category !== 'all' && icons.includes(name)) {
      return category as IconCategory
    }
  }
  return 'other'
}

export const getIconByName = (name: string) => {
  if (hasIcon(name)) {
    return (LucideIcons as Record<string, unknown>)[name]
  }
  return null
}

// 导出分类数据
export { iconsByCategory }

// 导出所有可用图标名称(用于搜索提示等)
export const allIconNames = iconsByCategory.all
