/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBackground: typeof import('./components/base/background/BaseBackground.vue')['default']
    BaseButton: typeof import('./components/base/button/BaseButton.vue')['default']
    BaseContainer: typeof import('./components/base/container/BaseContainer.vue')['default']
    BaseDialog: typeof import('./components/base/modal/BaseDialog.vue')['default']
    BaseIframe: typeof import('./components/base/iframe/BaseIframe.vue')['default']
    BaseInput: typeof import('./components/base/input/BaseInput.vue')['default']
    BaseModal: typeof import('./components/base/modal/BaseModal.vue')['default']
    BasePanel: typeof import('./components/modules/base-panel/index.vue')['default']
    BasePanelRoot: typeof import('./components/modules/base-panel/components/BasePanelRoot.vue')['default']
    BaseSelect: typeof import('./components/base/select/BaseSelect.vue')['default']
    BaseSwitch: typeof import('./components/base/switch/BaseSwitch.vue')['default']
    BaseTable: typeof import('./components/modules/table/BaseTable.vue')['default']
    BaseVanishingInput: typeof import('./components/base/input/vanishing/BaseVanishingInput.vue')['default']
    BeautifiedIframe: typeof import('./components/base/iframe/BeautifiedIframe.vue')['default']
    CategoryTabs: typeof import('./components/modules/navigation/components/CategoryTabs.vue')['default']
    GlowBox: typeof import('./components/modules/navigation/components/effect/GlowBox.vue')['default']
    HaloSearch: typeof import('./components/modules/search/HaloSearch.vue')['default']
    MagneticCard: typeof import('./components/modules/navigation/components/effect/MagneticCard.vue')['default']
    Menu: typeof import('./components/modules/menu/index.vue')['default']
    MenuRender: typeof import('./components/modules/menu/components/MenuRender.vue')['default']
    MenuRoot: typeof import('./components/modules/menu/components/MenuRoot.vue')['default']
    ModernSearch: typeof import('./components/modules/search/ModernSearch.vue')['default']
    MorphingCategoryTabs: typeof import('./components/modules/navigation/components/MorphingCategoryTabs.vue')['default']
    MotionWrapper: typeof import('./components/modules/navigation/components/effect/MotionWrapper.vue')['default']
    Navbar: typeof import('./components/modules/navbar/index.vue')['default']
    NavHeader: typeof import('./components/modules/navigation/components/NavHeader.vue')['default']
    NavigationCard: typeof import('./components/modules/navigation/components/NavigationCard.vue')['default']
    NavigationGrid: typeof import('./components/modules/navigation/components/NavigationGrid.vue')['default']
    NavigationPage: typeof import('./components/modules/navigation/NavigationPage.vue')['default']
    PanelMenuRecursive: typeof import('./components/modules/base-panel/components/PanelMenuRecursive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/modules/navigation/components/SearchBox.vue')['default']
    SearchBoxAI: typeof import('./components/modules/search/SearchBoxAI.vue')['default']
    SearchEngineBox: typeof import('./components/modules/search/SearchEngineBox.vue')['default']
    SettingsLayout: typeof import('./components/business/settings-layout/SettingsLayout.vue')['default']
    SunBreadcrumb: typeof import('./components/business/sun-breadcrumb/SunBreadcrumb.vue')['default']
    SunConfirmDialog: typeof import('./components/business/sun-confirm-dialog/SunConfirmDialog.vue')['default']
    SunForm: typeof import('./components/business/sun-form/SunForm.vue')['default']
    SunIconPicker: typeof import('./components/business/sun-icon-picker/SunIconPicker.vue')['default']
    SunNavigationCards: typeof import('./components/business/sun-navigation/SunNavigationCards.vue')['default']
    SunNavigationCarousel: typeof import('./components/business/sun-navigation/SunNavigationCarousel.vue')['default']
    SunSearch: typeof import('./components/business/sun-search/SunSearch.vue')['default']
    SunTable: typeof import('./components/business/sun-table/SunTable.vue')['default']
  }
}
